/**
 * modules/coach-ai/lib/export-engine.ts
 *
 * Premium PDF export engine for Coach AI Executive Briefings.
 * Uses jsPDF (already a project dependency) — client-side only.
 */

import jsPDF from 'jspdf';

interface ExportMetadata {
  timestamp: Date;
  healthScore?: number;
  query: string;
}

// ─── Colour Palette ───────────────────────────────────────────────────────────
const ORANGE   = [234, 88,  12]  as [number, number, number]; // orange-600
const DARK     = [17,  24,  39]  as [number, number, number]; // gray-900
const MID      = [75,  85,  99]  as [number, number, number]; // gray-600
const LIGHT    = [156, 163, 175] as [number, number, number]; // gray-400
const RULE     = [229, 231, 235] as [number, number, number]; // gray-200
const PAGE_BG  = [249, 250, 251] as [number, number, number]; // gray-50

// ─── Layout constants (mm) ───────────────────────────────────────────────────
const MARGIN   = 18;
const PAGE_W   = 210;
const PAGE_H   = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;

// ─── Markdown → token stream ─────────────────────────────────────────────────
type Token =
  | { type: 'h1' | 'h2' | 'h3'; text: string }
  | { type: 'bullet';            text: string }
  | { type: 'blank' }
  | { type: 'text';              text: string; bold?: boolean };

function parseMarkdown(content: string): Token[] {
  const tokens: Token[] = [];
  const lines = content.split('\n');

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (line.startsWith('### ')) {
      tokens.push({ type: 'h3', text: line.slice(4) });
    } else if (line.startsWith('## ')) {
      tokens.push({ type: 'h2', text: line.slice(3) });
    } else if (line.startsWith('# ')) {
      tokens.push({ type: 'h1', text: line.slice(2) });
    } else if (/^[-*]\s/.test(line)) {
      tokens.push({ type: 'bullet', text: line.replace(/^[-*]\s+/, '') });
    } else if (line.trim() === '') {
      tokens.push({ type: 'blank' });
    } else {
      // Strip inline bold markers for body text
      const stripped = line.replace(/\*\*(.+?)\*\*/g, '$1');
      tokens.push({ type: 'text', text: stripped });
    }
  }
  return tokens;
}

// ─── Page helpers ─────────────────────────────────────────────────────────────
function drawHeader(doc: jsPDF, page: number) {
  // Orange top bar
  doc.setFillColor(...ORANGE);
  doc.rect(0, 0, PAGE_W, 12, 'F');

  // Organisation name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('GHARPAYY  ·  ARENA OS', MARGIN, 7.5);

  // Page number (right-aligned)
  doc.text(`Page ${page}`, PAGE_W - MARGIN, 7.5, { align: 'right' });
}

function drawFooter(doc: jsPDF) {
  const y = PAGE_H - 8;
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 2, PAGE_W - MARGIN, y - 2);

  doc.setTextColor(...LIGHT);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('Confidential — Gharpayy Internal Use Only', MARGIN, y + 1);
  doc.text('Generated by Coach AI  ·  ARENA OS', PAGE_W - MARGIN, y + 1, { align: 'right' });
}

function newPage(doc: jsPDF, pageRef: { n: number }) {
  doc.addPage();
  pageRef.n++;
  drawHeader(doc, pageRef.n);
  drawFooter(doc);
  return 20; // top margin after header
}

// ─── Main export function ─────────────────────────────────────────────────────
export const exportOperationalReport = async (
  content: string,
  meta: ExportMetadata
): Promise<void> => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageRef = { n: 1 };

  drawHeader(doc, 1);
  drawFooter(doc);

  let y = 22; // starting Y below header

  // ── Cover block ─────────────────────────────────────────────────────────────
  // Orange accent rule
  doc.setFillColor(...ORANGE);
  doc.rect(MARGIN, y, 3, 28, 'F');

  // Title
  doc.setTextColor(...DARK);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Operational Briefing', MARGIN + 7, y + 9);

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MID);

  const formattedDate = meta.timestamp.toLocaleString('en-IN', {
    dateStyle: 'long',
    timeStyle: 'short',
    timeZone: 'Asia/Kolkata',
  });
  doc.text(`Generated: ${formattedDate}  ·  IST`, MARGIN + 7, y + 17);
  doc.text(`Subject: ${meta.query}`, MARGIN + 7, y + 23);

  y += 36;

  // Health score badge (if present)
  if (meta.healthScore !== undefined) {
    const score = meta.healthScore;
    const colour: [number, number, number] =
      score >= 75 ? [22, 163, 74] : score >= 50 ? [234, 88, 12] : [220, 38, 38];

    doc.setFillColor(249, 250, 251);
    doc.setDrawColor(...colour);
    doc.setLineWidth(0.6);
    doc.roundedRect(MARGIN, y, CONTENT_W, 14, 2, 2, 'FD');

    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colour);
    doc.text('ORGANISATION HEALTH SCORE', MARGIN + 5, y + 5.5);

    doc.setFontSize(16);
    doc.text(`${score} / 100`, MARGIN + 5, y + 12);

    // Status label
    const label = score >= 75 ? 'HEALTHY' : score >= 50 ? 'AT RISK' : 'CRITICAL';
    doc.setFontSize(8);
    doc.text(label, PAGE_W - MARGIN - 5, y + 9, { align: 'right' });

    y += 20;
  }

  // Divider
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 6;

  // ── Render content tokens ────────────────────────────────────────────────────
  const tokens = parseMarkdown(content);
  const BOTTOM_LIMIT = PAGE_H - 20;

  for (const token of tokens) {
    if (y > BOTTOM_LIMIT) {
      y = newPage(doc, pageRef);
    }

    switch (token.type) {
      case 'h1': {
        y += 4;
        doc.setFillColor(...ORANGE);
        doc.rect(MARGIN, y, CONTENT_W, 0.7, 'F');
        y += 3;
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...DARK);
        doc.text(token.text.toUpperCase(), MARGIN, y + 5);
        y += 10;
        break;
      }

      case 'h2': {
        y += 3;
        doc.setFillColor(...ORANGE);
        doc.rect(MARGIN, y + 3, 2.5, 5.5, 'F');
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...DARK);
        doc.text(token.text, MARGIN + 5, y + 7.5);
        y += 12;
        break;
      }

      case 'h3': {
        doc.setFontSize(9.5);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...ORANGE);
        doc.text(token.text.toUpperCase(), MARGIN, y + 5);
        y += 8;
        break;
      }

      case 'bullet': {
        // Dot
        doc.setFillColor(...ORANGE);
        doc.circle(MARGIN + 1.5, y + 2.2, 0.8, 'F');

        // Wrapped text
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...MID);
        const lines = doc.splitTextToSize(token.text, CONTENT_W - 6);
        lines.forEach((line: string, i: number) => {
          if (i > 0 && y + 5 > BOTTOM_LIMIT) y = newPage(doc, pageRef);
          doc.text(line, MARGIN + 5, y + 4 + i * 4.5);
        });
        y += 4 + lines.length * 4.5;
        break;
      }

      case 'blank': {
        y += 3;
        break;
      }

      case 'text': {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...MID);
        const lines = doc.splitTextToSize(token.text, CONTENT_W);
        lines.forEach((line: string, i: number) => {
          if (i > 0 && y + 5 > BOTTOM_LIMIT) y = newPage(doc, pageRef);
          doc.text(line, MARGIN, y + 4 + i * 4.5);
        });
        y += 4 + lines.length * 4.5;
        break;
      }
    }
  }

  // ── Final rule + sign-off ────────────────────────────────────────────────────
  if (y + 18 > BOTTOM_LIMIT) {
    y = newPage(doc, pageRef);
  }

  y += 6;
  doc.setDrawColor(...RULE);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 4;

  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(...LIGHT);
  doc.text('End of Executive Briefing  ·  Powered by Coach AI on ARENA OS', MARGIN, y + 4);

  // ── Trigger download ─────────────────────────────────────────────────────────
  const fileName = `Gharpayy-Briefing-${meta.timestamp.getTime()}.pdf`;
  doc.save(fileName);
};
